In [69]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier,AdaBoostRegressor,RandomForestRegressor,GradientBoostingRegressor
import warnings
warnings.filterwarnings("ignore")

In [28]:
data = pd.read_csv('Data/iris.csv')
data

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [29]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]
print("Shape of X is %s and shape of y is %s"%(X.shape,y.shape))

Shape of X is (150, 4) and shape of y is (150,)


In [30]:
total_classes = y.nunique()
print("Number of unique species in dataset are: ",total_classes)

Number of unique species in dataset are:  3


In [31]:
distribution = y.value_counts()
print(distribution)

0    50
1    50
2    50
Name: Species, dtype: int64


In [32]:
X_train,X_val,Y_train,Y_val = train_test_split(X,y,test_size=0.25,random_state=28)

In [33]:
adb = AdaBoostClassifier()
adb_model = adb.fit(X_train,Y_train)

In [34]:
print("The accuracy of the model on validation set is", adb_model.score(X_val,Y_val))

The accuracy of the model on validation set is 0.9210526315789473


In [36]:
adb_model.get_params()

{'algorithm': 'SAMME.R',
 'base_estimator': None,
 'learning_rate': 1.0,
 'n_estimators': 50,
 'random_state': None}

In [38]:
adb_model.predict(X_val)

array([0, 1, 1, 0, 2, 1, 2, 1, 1, 0, 2, 0, 1, 1, 2, 0, 2, 2, 2, 1, 0, 0,
       1, 2, 1, 0, 2, 2, 0, 1, 0, 2, 1, 0, 2, 1, 2, 1], dtype=int64)

In [39]:
Y_val

24     0
134    2
81     1
14     0
114    2
93     1
128    2
66     1
59     1
35     0
101    2
15     0
50     1
51     1
130    2
48     0
120    2
124    2
147    2
62     1
0      0
36     0
53     1
70     1
73     1
49     0
105    2
136    2
9      0
52     1
21     0
144    2
92     1
27     0
77     1
75     1
103    2
56     1
Name: Species, dtype: int64

In [59]:
airline = pd.read_csv('Data/AirPassengers.csv')
airline['Month'] = pd.to_datetime(airline['Month'])
#airline.set_index(airline['Month'])
#airline.index = airline['Month']
#airline = airline.drop('Month',axis=1)

In [60]:
airline

Month  #Passengers
0   1949-01-01          112
1   1949-02-01          118
2   1949-03-01          132
3   1949-04-01          129
4   1949-05-01          121
..         ...          ...
139 1960-08-01          606
140 1960-09-01          508
141 1960-10-01          461
142 1960-11-01          390
143 1960-12-01          432

[144 rows x 2 columns]

In [62]:
X = airline.iloc[:,[0]]
Y = airline.iloc[:,[1]]


Month
0   1949-01-01
1   1949-02-01
2   1949-03-01
3   1949-04-01
4   1949-05-01
..         ...
139 1960-08-01
140 1960-09-01
141 1960-10-01
142 1960-11-01
143 1960-12-01

[144 rows x 1 columns]

In [63]:
X_train,X_val,Y_train,Y_val = train_test_split(X,Y,test_size=0.25)

In [64]:
X_train

Month
55  1953-08-01
135 1960-04-01
90  1956-07-01
54  1953-07-01
23  1950-12-01
..         ...
76  1955-05-01
79  1955-08-01
9   1949-10-01
59  1953-12-01
70  1954-11-01

[108 rows x 1 columns]

In [65]:
adb = AdaBoostRegressor()
adb_model = adb.fit(X_train,Y_train)

In [66]:
print("The accuracy of the model on validation set is", adb_model.score(X_val,Y_val))

The accuracy of the model on validation set is 0.9061963911596714


In [67]:
adb_model.predict(X_val)

array([186.8125    , 229.75      , 460.18181818, 135.09090909,
       325.28571429, 244.72727273, 460.18181818, 342.35      ,
       186.8125    , 239.5       , 386.23529412, 473.25      ,
       194.8       , 138.2173913 , 325.28571429, 375.96      ,
       408.68      , 134.9       , 134.9       , 342.35      ,
       307.75      , 424.11111111, 460.18181818, 421.29032258,
       134.9       , 340.25      , 134.9       , 408.68      ,
       239.5       , 307.75      , 397.28571429, 186.8125    ,
       135.09090909, 194.8       , 342.35      , 229.75      ])

In [70]:
#Y_val

In [71]:
rf = RandomForestRegressor()
rf_model = rf.fit(X_train,Y_train)

In [72]:
print("The accuracy of the model on validation set is", rf_model.score(X_val,Y_val))

The accuracy of the model on validation set is 0.9631848141939432


In [73]:
rf_model.predict(X_val)

array([190.84, 225.85, 397.36, 142.66, 285.86, 244.27, 380.98, 323.21,
       186.64, 214.58, 425.17, 485.3 , 213.56, 147.29, 281.92, 365.52,
       391.81, 131.69, 109.02, 380.96, 328.83, 459.26, 516.36, 440.96,
       128.86, 315.25, 127.19, 387.77, 276.45, 304.41, 351.16, 172.17,
       151.64, 192.93, 323.1 , 226.42])

In [74]:
gbr = GradientBoostingRegressor()
gbr_model = rf.fit(X_train,Y_train)

In [75]:
print("The accuracy of the model on validation set is", gbr_model.score(X_val,Y_val))

The accuracy of the model on validation set is 0.9612982970605412


In [76]:
gbr_model.predict(X_val)

array([190.51, 228.22, 398.63, 142.8 , 281.01, 241.29, 377.28, 323.14,
       184.54, 216.32, 424.79, 476.28, 211.07, 145.21, 283.18, 371.73,
       396.62, 133.4 , 109.55, 382.98, 333.46, 450.75, 504.15, 458.51,
       124.94, 314.73, 127.21, 391.16, 283.04, 296.64, 355.64, 171.75,
       151.37, 191.43, 337.53, 222.72])